import Banner from "./components/Banner";
import Card from "./components/Card";
import Footer from "./components/Footer";
import Main from "./components/Main";
import Navbar from "./components/Navbar";
import Template from "./components/Template";
import Testimonial from "./components/Testimonial";

  export const metadata = {
    title: "storexpert | home",
    description: "Generated by create next app",
  };

export default function Home() {

  return (
    <main>
      <Navbar/>
      <Main/>
      <Banner/>
      <Card/>
      <Testimonial/>
      <Template/>
      <Footer/>
    </main>
  );
}
