import Navbar from "../components/Navbar";
import Login from "../components/auth/Login";


  export const metadata = {
    title: "storexpert | login",
    description: "Generated by create next app",
  };

const page = () => {
  return (
    <div>
      <Navbar/>
      <Login/>
    </div>
  )
}

export default page
