import Navbar from "../components/Navbar";
import SignUp from "../components/auth/SignUp";


  export const metadata = {
    title: "storexpert | signup",
    description: "Generated by create next app",
  };

const page = () => {
  return (
    <div>
      <Navbar/>
      <SignUp/>
    </div>
  )
}

export default page
