import Navbar from "../components/Navbar";
import PricingPage from "../components/pricing/PricingPage";

  export const metadata = {
    title: "storexpert | pricing",
    description: "Generated by create next app",
  };

const page = () => {
  return (
    <div>
      <Navbar/>
      <PricingPage/>
    </div>
  )
}

export default page
